export enum ActionsStoreType {
  UPDATE_ITEM_CART = 'INCREASE_ITEM_CART',
  ADD_ITEM_CART = 'ADD_ITEM_CART',
  CLEAR_CART = 'CLEAR_CART',
  REMOVE_ITEM_CART = 'REMOVE_ITEM_CART',
  FINALIZE_PURCHASE = 'FINALIZE_PURCHASE',
}
